### ISSUE TITLE
Error code 404 with slither-analyzer@ https://github.com/crytic/slither/archive/dev-triage-db.tar.gz 

### ISSUE THREAD

**Issue by nguyenzung** [crytic/slither-action#88]
Recently, there is an issue with my project that I am working on. It worked perfectly before. 

Action link: https://github.com/tokamak-network/tokamak-thanos/actions/runs/9770909664/job/26972844527

![Screenshot from 2024-07-03 09-29-21](https://github.com/crytic/slither-action/assets/57292598/820bc4ce-b859-4c41-8e0e-7dfcd438897e)

**Comment by elopez** [comment]
Hi! It looks like you have `slither-version: dev-triage-db` set on your action config. That's an older dev branch on the Slither repo that was probably cleaned up recently. i see it [has been merged already since a few versions ago](https://github.com/crytic/slither/commit/3163e248dc2d4f0909f31abba513c99b5e372ebf) so you should be able to use a stable release now (e.g. `slither-version: "0.10.3"`).
